### PR TITLE
Update and configure the new react-select package

### PR DESCRIPTION
**Pull request by dobladov**
When the issue is fixed  https://github.com/babel/babel-eslint/issues/530

"indent": ["error", 2], // Change to 
"template-curly-spacing" : "off"   // Remove

### CODE REVIEW

**Comment by literarymachine** [comment]
@dobladov in the old version, hitting the comma automatically created a new tag. Is it possible to also configure this for this version?

**Comment by dobladov** [comment]
At the moment I can't find any props to do this on the new version, in the examples https://jedwatson.github.io/react-select/ there is only one doing this `GitHub users`, the link to source is broken because it links to and old example, I found the code but I don't see any prop that sets this behavior https://github.com/JedWatson/react-select/blob/v1.x/examples/src/components/GithubUsers.js

**Comment by dobladov** [comment]
Two other related issues, both referencing the old version and the prop `shouldKeyDownEventCreateNewOption` does not seem to exists anymore.

[Why was comma create new tag functionality removed?](https://github.com/JedWatson/react-select/issues/987)
[Adding Custom Tag in single value mode does not allow you to enter a comma](https://github.com/JedWatson/react-select/issues/1671)

**Comment by literarymachine** [comment]
> Two other related issues, both referencing the old version and the prop shouldKeyDownEventCreateNewOption does not seem to exists anymore.

This is bad, because it is one of the reasons we introduced a custom tag widget in the first place. We might have to stay with the old version for now then.

**Pull request closed without merging**
