### PR TITLE
Add floating close button

### PR DESCRIPTION
**Pull request by dobladov**
Fixes: https://github.com/hbz/oerworldmap/issues/1521

### CODE REVIEW

**Comment by literarymachine** [comment]
> The only problem with the background is to click it by mistake while editing, in case of implemnting it we should prompt the user if he wants to go back when he is adding or editing.

Yep, we had that in the old UI with a simple JS `prompt` I think.

**Comment by formimkontext** [comment]
i would prefer a white x on transparent blue background. see: 

201801-desktop1280px-countryview

**Comment by literarymachine** [comment]
This is about closing the single resource view, not the country view.

**Comment by formimkontext** [comment]
i know. this is just an examle for the styling and position of an closing button (x) on a transparent blue background.

**Comment by dobladov** [comment]
Deprecated pull request in favour of https://github.com/hbz/oerworldmap-ui/pull/426

**Pull request closed without merging**
