### PR TITLE
Fix keyword list

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes hbz/oerworldmap#1924

### CODE REVIEW

**Comment by gandalfar** [comment]
The code change looks good to me. I can't (yet) test the editing part of the code as I'm still setting up auth.

**Comment by literarymachine** [comment]
@dr0i please deploy to beta.

**Comment by dr0i** [comment]
Deplyoed to beta.

**Comment by literarymachine** [comment]
@dr0i please deploy to production.

**Pull request merged**
