### PR TITLE
Fix display of admin only fields

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes https://github.com/hbz/oerworldmap/issues/1921

### CODE REVIEW

**Comment by literarymachine** [comment]
@dr0i please deploy to beta.

**Comment by dr0i** [comment]
Hi @literarymachine , merging this (as the last of some other PRs) I got a conflict (which I _think_ i solved properly). Don't know how to handle this:
1. you may just want to do a "functional" review as all PRs (inculded this) are deployed to beta, OR
2. you may want to e.g. push me the solved conflict into this PR to have a glance at the code.

**Comment by literarymachine** [comment]
@dr0i I can't see the conflict, which commit caused it?

**Comment by dr0i** [comment]
I think it's this one:
> commit 33509e1834bb631f2e6756b6ca02cdb03ce13523
Author: Felix Ostrowski <felix.ostrowski@googlemail.com>
Date:   Mon Aug 10 15:45:40 2020 +0200
>    Render only edit or view instead of CSS hiding
>    Fixes hbz/oerworldmap#1915

**Comment by literarymachine** [comment]
@dr0i please deploy to production.

**Pull request merged**
