### PR TITLE
Updates 'Call for tender' value

### PR DESCRIPTION
**Pull request by gandalfar**
This PR updates "Call for tender" to be "Call for tender/proposal". It's rebased from https://github.com/hbz/oerworldmap-ui/pull/629 .

To deploy, from `oerworldmap-ui ` (please change `http://localhost:9000` to correct API location)

```
curl -H "Content-type: application/json" http://localhost:9000/import/ -d @src/json/policyTypes.json
```

Ref: https://github.com/hbz/oerworldmap/issues/1937

### CODE REVIEW

**Review by literarymachine — APPROVED** [review]
+1

**Comment by literarymachine** [comment]
@dr0i please deploy to beta.

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by gandalfar** [comment]
I wonder if deploy/ingestion didn't work correctly, as frontend still shows wrong tender label, but in edit it's correct: https://beta.oerworldmap.org/resource/urn:uuid:b3ecd503-2823-4d59-b2b9-f778f6bcbbef

**Comment by literarymachine** [comment]
> I wonder if deploy/ingestion didn't work correctly

Yes, @dr0i did you run the cURL command from https://github.com/hbz/oerworldmap-ui/pull/633#issue-473181746?

**Comment by acka47** [comment]
@literarymachine @gandalfar Just to let you know, @dr0i had to take some days off this week and hasn't been working since Tuesday. He probably will be back on Monday.

**Comment by dr0i** [comment]
Yes, indeed I forgot to import the policy type  (http://localhost:9000 is the right place - opened a new PR to make the port of the play API more overt), restarted everything, but cannot the the label updated in the German version when clicking in https://beta.oerworldmap.org/resource/urn:uuid:b3ecd503-2823-4d59-b2b9-f778f6bcbbef at "Also available in: German" -  only the title is changed to German, the rest (as for the label of the policy type) sticks to English. However, if I switch to German using the icon at the top bar to switch to German everything is switched correctly. Shall I open a new issue for this?

**Comment by literarymachine** [comment]
> "Also available in: German" - only the title is changed to German, the rest (as for the label of the policy type) sticks to English. However, if I switch to German using the icon at the top bar to switch to German everything is switched correctly. Shall I open a new issue for this?

`Also available in` only refers to the data entered by users. This is expected behavior, no need for an issue!

**Comment by gandalfar** [comment]
It's working correctly now. Thanks.

@dr0i  please deploy to production

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
