### PR TITLE
Fix missing user prop and login link

### LINKED ISSUE #641: Join us to comment has wrong link
Steps to reproduce:

1. Go to - https://oerworldmap.org/resource/urn:uuid:a765eeb4-ef62-4a6c-a17d-64818983f276
2. Click on "Join us to comment!" and receive an error

It seems that link should be somewhat like:
/auth/realms/oerworldmap/login-actions/registration?client_id=account&tab_id=-pSb96LGTBU

I know that this is a something from .env so it just needs to be applied correctly.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes hbz/oerworldmap#1947, fixes #641

### CODE REVIEW

**Review by gandalfar — APPROVED** [review]

**Comment by literarymachine** [comment]
I am pretty sure the problem @gandalfar describes in https://github.com/hbz/oerworldmap/issues/1947#issuecomment-683806262 is local to his dev setup.

@dr0i please deploy this to beta so we can check there!

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by gandalfar** [comment]
Checked on beta and works correctly. @dr0i please deploy to production

**Comment by dr0i** [comment]
Deployed to production. Closed.

**Pull request merged**
