### PR TITLE
Update information about the world map team

### PR DESCRIPTION
**Pull request by acka47**

### CODE REVIEW

**Comment by literarymachine** [comment]
Updating this information in English now requires to also do so for the other languages: https://github.com/hbz/oerworldmap-ui/pull/564/files

**Comment by acka47** [comment]
Uh, you mean directly on GitHub and not via CrowdIn? I am afraid that would lead to problems we had with CrowdIn in the past as CrowdIn sees itself as the master for translations...

**Comment by literarymachine** [comment]
> Uh, you mean directly on GitHub and not via CrowdIn?

No, on CrowdIn. The link was just to show you that the re-structuring did not automatically make it to the other languages.

**Comment by acka47** [comment]
Ah, ok

**Pull request merged**
