### PR TITLE
Add Collection type to UI

### PR DESCRIPTION
**Pull request by literarymachine**
See hbz/oerworldmap#1939

### CODE REVIEW

**Review by gandalfar — APPROVED** [review]
Works great, thanks.

**Comment by gandalfar** [comment]
I've added labels and a small CSS adjustment to make header a bit more readable.

@dr0i please deploy to beta

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by gandalfar** [comment]
@dr0i please deploy to production

**Comment by dr0i** [comment]
Uh, sorry for being a "bit" late.
Deployed and merged. Closed.

**Pull request merged**
