### PR TITLE
Add reference number field

### PR DESCRIPTION
**Pull request by literarymachine**
This complements https://github.com/hbz/oerworldmap/pull/1942, see hbz/oerworldmap#1938

### CODE REVIEW

**Review by gandalfar — APPROVED** [review]
I've confirmed it works correctly. Thanks for implementing this.

**Comment by literarymachine** [comment]
@dr0i please deploy to beta.

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by gandalfar** [comment]
@dr0i I don't see these changes on beta. Is this because of failed compilation step described in https://github.com/hbz/oerworldmap-ui/issues/640 ?

**Comment by literarymachine** [comment]
This is because the changes in the UI are rather cosmetic (labels etc), the actual change in the data model happens in https://github.com/hbz/oerworldmap/pull/1942. Sorry, forgot to assign @dr0i!

**Comment by dr0i** [comment]
As deployed https://github.com/hbz/oerworldmap/pull/1942 to beta, please have a look again at this @gandalfar .

**Comment by gandalfar** [comment]
I've checked and it's still not showing up. I've rechecked on a local dev and it's showing up correctly. 

@literarymachine does this need any index/db to be rebuilt?

**Comment by literarymachine** [comment]
The schema changes from https://github.com/hbz/oerworldmap/pull/1942 are not reflected in https://beta.oerworldmap.org/assets/json/schema.json. @dr0i did you restart the API after merging?

**Comment by dr0i** [comment]
@literarymachine yeah I did restart the API , but didn't 'sbt stage' before. This just restarts the old code. I will open a PR to document it properly, since the README tells to `sbt run` but that's not cleaning and rebuilding the `target`.

**Comment by gandalfar** [comment]
This is now working correctly on beta. Please deploy to production @dr0i .

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
