### PR TITLE
Fix labels in policy type vocab

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes hbz/oerworldmap#1914

### CODE REVIEW

**Comment by literarymachine** [comment]
@trugwaldsaenger I just realized there are no German labels for the policy sub types. You can fix them here:

https://github.com/hbz/oerworldmap-ui/edit/1914-vocabLabels/src/json/policies.json

and then "Commit directly to the `1914-vocabLabels` branch"!

**Comment by literarymachine** [comment]
@dr0i please deploy to beta.

**Comment by dr0i** [comment]
Deplyoed to beta.

**Comment by literarymachine** [comment]
This currently fixes it for the input form where previously also the Portuguese values where shown:

image

image

It does not fix it yet for the filter section (on beta, English is display when it should be German):

image

**Comment by literarymachine** [comment]
@dr0i I added another fix, could you deploy this to beta again? Thanks!

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by dr0i** [comment]
Ok deployed your integration-branch to beta.

**Comment by literarymachine** [comment]
@dr0i I added a fix for https://github.com/hbz/oerworldmap/issues/1914#issuecomment-675406812, please deploy to beta once again. Thanks!

**Comment by literarymachine** [comment]
@dr0i you might as well deploy this to production.

**Comment by literarymachine** [comment]
@dr0i please also ingest the updated vocab to the API:

`curl -H "Content-type: application/json" http://localhost:9000/import/ -d @src/json/policies.json`

**Comment by dr0i** [comment]
fyi: did the curling just now.

**Pull request merged**
